name: ðŸš€ Deploy Portfolio
on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Sync_to_AwardSpace_JJSPort
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v3

      - name: ðŸ“‚ SFTP Deploy
        uses: pressidium/sftp-deploy@v1
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          pass: ${{ secrets.FTP_PASSWORD }}
          port: 221
          local_path: './*'
          remote_path: '/home/www/jherichsilas.com/'